# Generated by Django 4.0.3 on 2022-03-15 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_candidat_etat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidat',
            name='etat',
            field=models.CharField(choices=[('en cours de traitement', 'INPROCESS'), ('accepté', 'ACCECTED'), ('rejeté', 'REJECTED'), ("sur la liste d'attente", 'WAITING')], default='en cours de traitement', max_length=22),
        ),
    ]
