# Generated by Django 4.0.3 on 2022-03-15 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_candidat_etat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidat',
            name='etat',
            field=models.CharField(choices=[('en cours de traitement', 'en cours de traitement'), ('accepté', 'accepté'), ('rejeté', 'rejeté'), ("sur la liste d'attente", "sur la liste d'attente")], default="sur la liste d'attente", max_length=22),
        ),
    ]
