# Generated by Django 4.0.3 on 2022-03-14 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Centre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('adresse', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Centre',
                'verbose_name_plural': 'Centres',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.CharField(max_length=50)),
                ('dateConcours', models.DateField()),
                ('date_ouverture_depot', models.DateField()),
                ('date_limite_depot', models.DateField()),
                ('date_depot_releves', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Session',
                'verbose_name_plural': 'Sessions',
            },
        ),
        migrations.CreateModel(
            name='Candidat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=50)),
                ('nom', models.CharField(max_length=50)),
                ('numDossier', models.CharField(max_length=50)),
                ('date_depot', models.DateTimeField(auto_now_add=True)),
                ('etat', models.CharField(choices=[('INPROCESS', 'En cours de traitement'), ('ACCEPT', 'Accepté'), ('REJECT', 'Rejeté')], default='INPROCESS', max_length=22)),
                ('centre_examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendapp.centre')),
            ],
            options={
                'verbose_name': 'Candidat',
                'verbose_name_plural': 'Candidats',
            },
        ),
    ]
